
cherry:
  runner:
    refreshTopicsInSeconds: 10

  connectorslib:
    uploadpath: ./localstorage/upload
    classloaderpath: ./localstorage/classloader
    forcerefresh: true

  initialisation:
    runners:
      - https://github.com/camunda-community-hub/camunda-8-connector-pdf/releases/download/3.1.1/pdf-function-3.1.1.jar
      - https://github.com/camunda-community-hub/camunda-8-connector-zip/releases/download/1.0.0/ZIP-1.0.0.jar

  repository:
    - https://github.com/camunda-community-hub/

  runners:
    # the runtime load all embedded runners
    embeddedrunner: true

    # the runtime load ping runners
    pingrunner: false


  tenants:
    # Enable the tenants functionality "autoDectection" implie to connect to Operate
    automaticDetection: true
    refreshTenantsInMinutes: 1
    tenants-ids:

# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

camunda:
  client:
    mode: saas
    auth:
      client-id: 2AJSqmrUHsnA4oBUQB1AO_sZXzTJoqre
      client-secret: 7SPYZDd6tPUSYh9FQeXWUVQRjIePz1nFaqo5_N1VsD.zaAN.hijdsCyJ_2zbN1Ca
    cloud:
      cluster-id: 3a20587e-9917-4be0-9fe6-87f90224c9ea
      region: lhr-1
camundajo:
  client:
    mode: saas
    auth:
      client-id: Riy18RliB0nYB5-ZyOG0v07DyVHHvwJW
      client-secret: iN6cw_7tv3mKpeg_nt.cLNfkohiS_.cu~nqvHVou5I_JFlVURG_q4c4zLXR5ZUBB
    cloud:
      cluster-id: fe65ee66-4bcf-4cb9-8acc-d2fc90618507
      region: dsm-1

server:
  port: 9081
logging.level.root: INFO
logging.level.io.camunda.cherry: INFO

spring.datasource:
  url: "jdbc:h2:file:./cherry.db"
  driver-class-name: "org.h2.Driver"
  username: "sa"
  password: "password"
spring.jpa.database-platform: "org.hibernate.dialect.H2Dialect"
org.hibernate.dialect: "H2Dialect"

